### ISSUE TITLE
Can you Add LRV-Instruction to your Paper or Repo

### ISSUE THREAD

**Issue by FuxiaoLiu** [wangcunxiang/LLM-Factuality-Survey#2]
Dear Authors:

Congrats on the impressive work!

Our paper "[Aligning Large Multi-Modal Model with Robust Instruction Tuning](https://arxiv.org/pdf/2306.14565.pdf)" (published in June) introduced GAVIE to evaluate hallucination of LLMs with vision modality. We are also the first to mitigate the hallucination of LVLMs, which is related to your work about factuality.

Really Appreciate it!

**Comment by wangcunxiang** [comment]
Thanks for your recommentation!
We will add this paper in the next version of our paper
