### ISSUE TITLE
关于 factuality 和 hallucination 的疑问

### ISSUE THREAD

**Issue by slchenchn** [wangcunxiang/LLM-Factuality-Survey#5]
您好， 您在论文中给出了【factuality】和【hallucination】的区分，如下图所示：
![image](https://github.com/wangcunxiang/LLM-Factuality-Survey/assets/21030154/bf6be520-2843-4cbf-b23c-5037975d2741)

但是我感觉文中【hallucination】的定义似乎和【instruction following】很像，想请问下您是如何区分【hallucination】和【instruction following】的？

**Comment by wangcunxiang** [comment]
我们的定义是follow GPT-4 technical report中的”produce content that is nonsensical or untruthful in relation to certain sources.” ，照我的理解，其中的certain sources也包括instruction。我没有研究过目前instruction following具体有哪些研究的内容，所以对这一块不是太了解，但是直观上，我觉得hallucination和instruction following应该是两个有交叠但各自有所侧重的方向，比如有些内容是follow instruction但是模型就是在胡编乱造，就是hallucination但不是instruction following issue。另外，按照这个表格来说，【hallucination】的定义和【instruction following】显然是有区别的，比如Non-Factual and Hallucinatied这一块可能是follow instruction的输出。
