### ISSUE TITLE
Request for adding a reference

### ISSUE THREAD

**Issue by youganglyu** [wangcunxiang/LLM-Factuality-Survey#6]
Dear Cunxiang,

I am writing to express my appreciation for your comprehensive and inspiring survey paper!

I want to bring to your attention our recent paper titled "[KnowTuning: Knowledge-aware Fine-tuning for Large Language Models](https://arxiv.org/abs/2402.11176)". In this work, we introduced KnowTuning, a method designed to explicitly and implicitly enhance the knowledge awareness of Large Language Models (LLMs). Our approach aims to improve the completeness, factuality, and logicality of knowledge-intensive question-answering tasks by improving the knowledge awareness of LLMs.

I think our method is relevant to the discussion in your survey paper, particularly in continuous SFT methods for factuality enhancement.

Once again, thank you for your excellent contribution to the field.

Best regards,

**Comment by wangcunxiang** [comment]
Hi, Yougang, thanks for your reference! 
We will add it in the next version.
