### ISSUE TITLE
May I know the tool to create the survey tree visualization

### ISSUE THREAD

**Issue by krishnakanthnakkav2** [wangcunxiang/LLM-Factuality-Survey#7]
Dear Authors, 

May I ask what tool you used to create the survey_tree.jpg visualization ? It is very effective and concise. 

Thanks

**Comment by wangcunxiang** [comment]
Hi, you can directly download the latex file in the arxiv page https://arxiv.org/abs/2310.07521 , Acess Paper -> TeX Source. The tree is in Figures/fig-tree.tex
